### ISSUE TITLE
Random crash on server

### ISSUE THREAD

**Issue by ghost** [ThePoultryMan/Particle-Moths#1]
Hello, my game crashed randomly on my server. Every time I tried to reconnect I got the same error:

java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at net.minecraft.block.RedstoneLampBlock.randomDisplayTick(RedstoneLampBlock:527)
	at net.minecraft.client.world.ClientWorld.randomBlockDisplayTick(ClientWorld:383)
	at net.minecraft.client.world.ClientWorld.doRandomBlockDisplayTicks(ClientWorld:358)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1892)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$ima000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:34022)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:795)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2453.method_9496(class_2453.java:527)
	at net.minecraft.class_638.method_2943(class_638.java:383)
	at net.minecraft.class_638.method_2941(class_638.java:358)

**Removing the mod helped and I was able to join the server.**

**Comment by ThePoultryMan** [comment]
Thank you for reporting this. This should be a simple fix, and I’ll get to updating as fast as I can.

**Comment by ThePoultryMan** [comment]
Fixed as of version 1.0.1, which has been released.

**Comment by ghost** [comment]
Thank you 😊
Maybe you want to create other particle mobs, like butterflies etc.
Greetings.
